// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woo.Api.Persistence;

#nullable disable

namespace Woo.Api.Persistence.Migrations
{
    [DbContext(typeof(WooDbContext))]
    [Migration("20260804095831_MergeHouseIntoSettlement")]
    partial class MergeHouseIntoSettlement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woo.Api.Features.Settlements.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kingdom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("Woo.Api.Features.Settlements.Settlement", b =>
                {
                    b.OwnsOne("Woo.Api.Features.Resources.ResourcePool", "Resources", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.HasKey("SettlementId");

                            b1.ToTable("Settlements");

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");

                            b1.OwnsMany("Woo.Api.Features.Resources.ResourceBalance", "Balances", b2 =>
                                {
                                    b2.Property<Guid>("SettlementId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Kind")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint");

                                    b2.HasKey("SettlementId", "Kind");

                                    b2.ToTable("ResourceBalances", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SettlementId");
                                });

                            b1.Navigation("Balances");
                        });

                    b.OwnsMany("Woo.Api.Features.Settlements.Building", "Buildings", b1 =>
                        {
                            b1.Property<Guid>("SettlementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTimeOffset?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("CompletesAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("StartedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("SettlementId", "Kind");

                            b1.ToTable("Buildings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SettlementId");
                        });

                    b.Navigation("Buildings");

                    b.Navigation("Resources")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
