// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woo.Api.Persistence;

#nullable disable

namespace Woo.Api.Persistence.Migrations
{
    [DbContext(typeof(WooDbContext))]
    partial class WooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woo.Api.Features.Houses.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kingdom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Houses", (string)null);
                });

            modelBuilder.Entity("Woo.Api.Features.Houses.House", b =>
                {
                    b.OwnsOne("Woo.Api.Features.Resources.ResourcePool", "Resources", b1 =>
                        {
                            b1.Property<Guid>("HouseId")
                                .HasColumnType("uuid");

                            b1.HasKey("HouseId");

                            b1.ToTable("Houses");

                            b1.WithOwner()
                                .HasForeignKey("HouseId");

                            b1.OwnsMany("Woo.Api.Features.Resources.ResourceBalance", "Balances", b2 =>
                                {
                                    b2.Property<Guid>("HouseId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Kind")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<long>("Amount")
                                        .HasColumnType("bigint");

                                    b2.HasKey("HouseId", "Kind");

                                    b2.ToTable("ResourceBalances", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("HouseId");
                                });

                            b1.Navigation("Balances");
                        });

                    b.OwnsOne("Woo.Api.Features.Settlements.Settlement", "Settlement", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("HouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("HouseId")
                                .IsUnique();

                            b1.ToTable("Settlements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HouseId");

                            b1.OwnsMany("Woo.Api.Features.Settlements.Building", "Buildings", b2 =>
                                {
                                    b2.Property<Guid>("SettlementId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Kind")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.Property<DateTimeOffset?>("CompletedAtUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset?>("CompletesAtUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset?>("StartedAtUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)");

                                    b2.HasKey("SettlementId", "Kind");

                                    b2.ToTable("Buildings", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SettlementId");
                                });

                            b1.Navigation("Buildings");
                        });

                    b.Navigation("Resources")
                        .IsRequired();

                    b.Navigation("Settlement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
